changelog:
  categories:
    - title: ⚠️ Breaking Changes
      labels:
        - breaking-change

    - title: ✨ New Features
      labels:
        - enhancement

    - title: ⚡ Fixes
      labels:
        - fix

    - title: 🌐 immichFrame WebApp
      labels:
        - ImmichFrame_Web

    - title: 💻📱 immichFrame ClientApp
      labels:
        - ImmichFrame_Client

    - title: 📓 Documentation
      labels:
        - documentation

    - title: 🔨 Maintenance
      labels:
        - maintenance
        - performance

    - title: 🚀 Other changes
      labels:
        - "*"
