---
name: 'Bug Report'
description: 'Report a bug'
labels:
  - 'bug'
body:
  - type: 'markdown'
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report.

        Please review the following requirements before submitting this issue type:

        1. Please try to give as much information as possible for us to be able to reproduce the issue and provide a quick fix.
        2. Please ensure an issue does not already exist for this potential bug.
        3. Please only provide a released specific version or versions. Latest is not a version. Only released stable versions should be reported here.
  - type: 'input'
    id: 'version'
    attributes:
      label: |
        Version
      description: |
        What version of ImmichFrame can you reproduce this bug on?
    validations:
      required: true
  - type: 'input'
    id: 'deployment'
    attributes:
      label: |
        Deployment Method
      description: |
        Where are you deploying ImmichFrame? e.g. Desktop, Android, Web
    validations:
      required: true
  - type: 'textarea'
    id: 'description'
    attributes:
      label: |
        Description
      description: |
        Describe the bug.
    validations:
      required: true
  - type: 'textarea'
    id: 'reproduction'
    attributes:
      label: |
        Reproduction
      description: |
        Describe how we can reproduce this issue. This should be step by step and should include detailed and specific information. Abstract or generic information should be avoided.
    validations:
      required: true
  - type: 'textarea'
    id: 'expectations'
    attributes:
      label: |
        Expectations
      description: |
        Describe the desired or expected results.
    validations:
      required: false
  - type: 'textarea'
    id: 'configuration'
    attributes:
      label: |
        Configuration
      description: |
        Provide a complete configuration file (Settings.xml).
      render: 'xml'
    validations:
      required: false
  - type: 'textarea'
    id: 'logs'
    attributes:
      label: |
        Logs
      description: |
        Provide complete logs if available.

        The template will automatically put this content in a code block so you can just paste it.
      render: 'shell'
    validations:
      required: false
  - type: 'checkboxes'
    id: 'checklist'
    attributes:
      label: |
        Pre-Submission Checklist
      description: |
        By submitting this issue confirm all of the following.
      options:
        - label: |
            This is a bug report and not a feature request
          required: true
        - label: |
            I have provided all of the required information to reproduce the bug (config, logs, etc.)
          required: true
        - label: |
            I have checked for related issues and checked the documentation
          required: true
...