services:
  immichframe_api:
    build:
      context: ..
      # target: final
    ports:
      - 8080:8080
    volumes:
      - C:\Users\Jan\Desktop\immichFrame_Config:/app/Config
      # - PATH/TO/CONFIG:/app/Config
  immichframe_kiosk:
    build:
      context: ../ImmichFrame.Kiosk
      # target: final
    ports:
      - 5173:5173
    volumes:
      - C:\Users\Jan\Desktop\immichFrame_Config:/app/Config
      # - PATH/TO/CONFIG:/app/Config
