networks:
  dev:
    driver: bridge

services:
  immichframe_nginx:
    image: ghcr.io/immichframe/immichframe_nginx:main
    restart: always
    ports:
      - "80:80"
    networks:
      - dev
  immichframe_api:
    image: ghcr.io/immichframe/immichframe_api:main
    restart: always
    volumes:
      - ~/immichFrame_Config:/app/Config
    networks:
      - dev
  immichframe_web:
    image: ghcr.io/immichframe/immichframe_web:main
    restart: always
    volumes:
      - ~/immichFrame_Config:/app/Config
    networks:
      - dev