services:
  immichframe_api:
    build:
      context: ..
      # target: final
    ports:
      - 8080:8080
    volumes:
      - PATH/TO/CONFIG:/app/Config
  immichframe_kiosk:
    build:
      context: ../ImmichFrame.Kiosk
      # target: final
    ports:
      - 3000:3000
    volumes:
      - PATH/TO/CONFIG:/app/Config
