services:
  immichframe:
    container_name: immichFrame
    image: ghcr.io/immichframe/immichframe:main
    restart: on-failure
    volumes:
      - PATH/TO/CONFIG:/app/Config
    ports:
      - "8080:8080"
    environment:
      TZ: "Europe/Berlin"