name: Build and Publish image to Docker Hub
on: [workflow_dispatch]

jobs:
  publish_images:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: build image
        run: |
          REGISTRY_NAME="ghcr.io"
          API_REPOSITORY=${{ github.repository_owner }}/immich-machine-learning
          WEB_REPOSITORY=${{ github.repository_owner }}/immichframe_web
          docker build . -t $REGISTRY_NAME/$API_REPOSITORY:latest
          docker build -t $REGISTRY_NAME/$WEB_REPOSITORY:latest -f immichFrame.Web/dockerfile --target prod immichFrame.Web
      - name: push image to docker hub
        run: |
          REGISTRY_NAME="ghcr.io"
          API_REPOSITORY=${{ github.repository_owner }}/immich-machine-learning
          WEB_REPOSITORY=${{ github.repository_owner }}/immichframe_web
          docker login --username ${{ github.repository_owner }} --password ${{ secrets.GH_PAT }} ghcr.io
          docker push $REGISTRY_NAME/$API_REPOSITORY:latest
          docker push $REGISTRY_NAME/$WEB_REPOSITORY:latest
