name: Send Release to Discord

on:
  release:
    types: [published]

jobs:
  send-discord-message:
    runs-on: ubuntu-latest

    steps:
      - name: Send Discord Webhook
        uses: actions/http-client@v2
        with:
          url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          method: POST
          headers: |
            Content-Type: application/json
          body: |
            {
              "content": "New Release:\n\n**Tag:** ${{ github.event.release.tag_name }}\n**Name:** ${{ github.event.release.name }}\n**Published At:** ${{ github.event.release.published_at }}\n\nCheck it out here: ${{ github.event.release.html_url }}"
            }
